########## 设置开发环境配置信息
###### 设置项目启用端口号
server:
  port: 9999
spring:
  ###### 配置项目应用名
  application:
    name: witmed-registry
  ###### 其中 Spring Boot Bean id 的 Override 机制
  main:
    allow-bean-definition-overriding: true
###### 配置 Eureka Service 信息
eureka:
  ##### 配置 Server 主机名
  instance:
    hostname: localhost
  #### 配置 Client 信息
  client:
    #### 配置注册中心将自己的服务在其中进行注册
    register-with-eureka: false
    ##### 禁止注册中心去其他注册中心查找服务
    fetch-registry: false
    ##### 设置其他 Client 连接注册中心地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka